name: Publish Colours

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: "0"

      - name: Configure Git User
        run: |
          git config --global user.email "petinga@sardine.dev"
          git config --global user.name "@$GITHUB_ACTOR"

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
          scope: "@sardine"
          cache: "npm"

      - name: "Setup npm"
        run: |
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Export types
        run: npm run types:emit

      - name: Build for unpkg
        run: npx esbuild ./dist/index.mjs --minify --outfile=./dist/index.min.js

      - name: Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npx changeset publish
          commit: "[ci] release"
          title: "[ci] release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
