name: Release Candidate

on:
  push:
    branches:
      - changeset-release/main
    paths-ignore:
      - "package.json"
      - "package-lock.json"
      - ".changeset/**"
      - "CHANGELOG.md"

jobs:
  publish-rc:
    name: Publish RC
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      repository-projects: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: "0"

      - name: Configure Git User
        run: |
          git config --global user.email "petinga@sardine.dev"
          git config --global user.name "@$GITHUB_ACTOR"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          scope: "@sardine"
          cache: "npm"

      - name: "Setup npm"
        run: |
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Export types
        run: npm run types:emit

      - name: Build for unpkg
        run: npx esbuild ./dist/index.mjs --minify --outfile=./dist/index.min.js

      - name: Publish Colour Release Candidate
        run: |
          npx changeset pre enter rc
          npx changeset version
          git add .
          git commit -m "chore: release candidate"
          npx changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
