name: Run Tests

on: [pull_request]

jobs:
  types:
    name: Type Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run types:check

  testing-on-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14", "16"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
