name: Run Tests

on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

jobs:
  types:
    name: Check ${{ matrix.test }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: ["types:check", "lint"]
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ${{ matrix.test }}
        run: npm run ${{ matrix.test }}

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["20", "22", "24"]

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
