name: Run Tests

on:
  pull_request:
    branches-ignore:
      - changeset-**

jobs:
  types:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run types:check

      - name: Check lint and format
        run: npm run rome:ci

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16", "18"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
